config/routes.rb
MobileResume::Application.routes.draw do
  get "finish/index"

  get "experience/index"

  get "experience/jobs"

  get "experience/school"

  get "experience/other"

  get "jobs/create"

  get "home/index"

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/experience_controller.rb
class ExperienceController < ApplicationController
  def index
  end

  def jobs
  end

  def school
  end

  def other
  end
end

app/controllers/finish_controller.rb
class FinishController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experience_helper.rb
module ExperienceHelper
end

app/helpers/finish_helper.rb
module FinishHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/experience/index.html.erb
<div class="navbar navbar-inner center">
<h1> Add Experiences </h1>
</div>
<div id="container">
    <%= link_to "Add School", "school", {:class=>"btn btn-large center"}%>
  <div class="clearfix"></div>
    <%= link_to "Add Jobs", "jobs", {:class=>"btn btn-large center"}%>
  <div class="clearfix"></div>
    <%= link_to "Add Other", "other", {:class=>"btn btn-large center"}%>
  <div class="clearfix"></div>
    <%= link_to "Done", finish_index_path, {:class=>"btn btn-large center"}%>
</div>

app/views/experience/jobs.html.erb
<div class="navbar navbar-inner center">
  <h1> Add Work Experience </h1>
</div>
<div id="container">
  <div id="form">
    <%= form_tag do %>
        <div class="form_entry">
          <%= label_tag(:name, "Company Name") %>
          <%= text_field_tag(:name) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:title, "Job Title") %>
          <%= text_field_tag(:title) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:start, "Start Date") %>
          <%= select_tag :startMonth, options_for_select(["Jan","Feb","Mar","Apr","May","June","July","Aug","Sep","Oct","Nov","Dec"]) %>
          <%= select_tag :startYear, options_for_select(["2013","2012","2011","2010"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:end, "End Date") %>
          <%= select_tag :endMonth, options_for_select(["Jan","Feb","Mar","Apr","May","June","July","Aug","Sep","Oct","Nov","Dec"]) %>
          <%= select_tag :endYear, options_for_select(["2013","2012","2011","2010"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:program, "Description (Optional)") %>
          <%= text_field_tag(:program) %>
        </div>
    <% end %>
      <%= link_to "Next", experience_index_path, {:class=>"btn btn-large center"} %>
  </div>
</div>

app/views/experience/other.html.erb
<div class="navbar navbar-inner center">
  <h1> Add Other Experience </h1>
</div>
<div id="container">
  <div id="form">
    <%= form_tag do %>
        <div class="form_entry">
          <%= label_tag(:name, "Name") %>
          <%= text_field_tag(:name) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:start, "Start Date") %>
          <%= select_tag :startMonth, options_for_select(["Jan","Feb","Mar","Apr","May","June","July","Aug","Sep","Oct","Nov","Dec"]) %>
          <%= select_tag :startYear, options_for_select(["2013","2012","2011","2010"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:end, "End Date") %>
          <%= select_tag :endMonth, options_for_select(["Jan","Feb","Mar","Apr","May","June","July","Aug","Sep","Oct","Nov","Dec"]) %>
          <%= select_tag :endYear, options_for_select(["2013","2012","2011","2010"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:program, "Description (Optional)") %>
          <%= text_field_tag(:program) %>
        </div>
    <% end %>
      <%= link_to "Next", experience_index_path, {:class=>"btn btn-large center"} %>
  </div>
</div>

app/views/experience/school.html.erb
<div class="navbar navbar-inner center">
  <h1> Add School </h1>
</div>
<div id="container">
  <div id="form">
    <%= form_tag do %>
        <div class="form_entry">
          <%= label_tag(:type, "School Type") %>
          <%= select_tag :type, options_for_select(["High School","College / University","Vocational","Medical"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:name, "School Name") %>
          <%= text_field_tag(:name) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:diploma, "Diploma") %>
          <%= select_tag :diploma, options_for_select(["High School","A.A.","A.S.","B.A.","B.S.","M.A.","M.S.","PhD","M.D.","Other"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:grad, "Graduation Date") %>
          <%= select_tag :gradSeason, options_for_select(["Spring","Summer","Fall"]) %>
          <%= select_tag :gradYear, options_for_select(["2013","2012","2011","2010"]) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:program, "Program") %>
          <%= text_field_tag(:program) %>
        </div>
    <% end %>
      <%= link_to "Next", experience_index_path, {:class=>"btn btn-large center"} %>
  </div>
</div>

app/views/finish/index.html.erb
<div class="navbar navbar-inner center">
  <h1> One last thing </h1>
</div>
<div id="container">
  <div id="form">
    <%= form_tag do %>
        <div class="form_entry">
          <%= label_tag(:password, "Password") %>
          <%= password_field_tag(:password) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:subscribe, "Subscribe to things?") %>
          <%= check_box_tag(:subscribe) %>
        </div>
        <div class="form_entry">
          <%= label_tag(:terms, "Agree to our terms?") %>
          <%= check_box_tag(:terms) %>
        </div>
    <% end %>
      <%= link_to "Finish!", home_index_path, {:class=>"btn btn-large center"} %>
  </div>
</div>

app/views/home/index.html.erb
<div class="navbar navbar-inner center">
    <h1> Mobile Resume Builder </h1>
</div>
<div id="container">
  <div id="form">
    <%= form_tag do %>
        <div class="form_entry">
        <%= label_tag(:name, "Name") %>
        <%= text_field_tag(:name) %>
        </div>
        <div class="form_entry">
        <%= label_tag(:email, "Email") %>
        <%= text_field_tag(:email) %>
        </div>
        <div class="form_entry">
        <%= label_tag(:city, "City") %>
        <%= text_field_tag(:city) %>
        </div>
        <div class="form_entry">
        <%= label_tag(:state, "State") %>
        <%= text_field_tag(:state) %>
        </div>
        <div class="form_entry">
        <%= label_tag(:zip, "Zip Code") %>
        <%= text_field_tag(:zip) %>
        </div>
    <% end %>
      <%= link_to "Get Started!", experience_index_path, {:class=>"btn btn-large center"} %>
  </div>
</div>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileResume</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page">
<%= yield %>
</div>
</body>
</html>